[C++][Gandiva] Implement Translate Function
s1mbi0se/arrow pull request #24
Opened 2021-12-15 21:19 UTC by ViniciusSouzaRoque

2021-12-17 13:41 UTC, anthonylouisbsb requested changes

2021-12-17 13:41 UTC, anthonylouisbsb commented on cpp/src/gandiva/gdv_function_stubs.cc
> +    return nullptr;
returns an empty string `""`

2021-12-17 13:41 UTC, anthonylouisbsb commented on cpp/src/gandiva/gdv_function_stubs.cc
> +    return nullptr;
ditto

2021-12-17 13:41 UTC, anthonylouisbsb commented on cpp/src/gandiva/gdv_function_stubs.cc
> +      continue;
is this `continue` necessary?

2021-12-20 09:39 UTC, ViniciusSouzaRoque commented on cpp/src/gandiva/gdv_function_stubs.cc
> +    return nullptr;
Done

2021-12-20 09:39 UTC, ViniciusSouzaRoque commented on cpp/src/gandiva/gdv_function_stubs.cc
> +    return nullptr;
Done

2021-12-20 09:40 UTC, ViniciusSouzaRoque commented on cpp/src/gandiva/gdv_function_stubs.cc
> +      continue;
no, i removed. 
done

2022-02-04 12:44 UTC, closed without merging